### ISSUE TITLE
How to make this work with composes

### ISSUE THREAD

**Issue by jole78** [StevenIseki/bootstrap-css#2]
I have a style.css with the following:

```
.page-header {
    /*composes: page-header from global;*/
    composes: page-header from 'bootstrap-css/type';
    margin: 0 0 20px;
}
```

That produces this error (webpack): Module not found: Error: Cannot resolve module 'bootstrap-css/type'

If I instead try this:
`composes: page-header from 'bootstrap-css';`
I get the following error:
Module build failed: CssSyntaxError: node_modules/bootstrap-css/index.js:3:1: Unknown word

This however:
`composes: page-header from global;`
does does get me the desired outcome since I have bootstrap as a separate css bundled.

Ideas/Comments?

**Comment by terencechow** [comment]
In my project using less I have no problem with `composes: btn from bootstrap/lib/buttons.css`

**Comment by svnm** [comment]
Can you provide a repo showing the issue, otherwise I will be taking @terencechow's advice that all is working as it is in the examples and will have to close this.
